# Generated by Django 5.2.8 on 2025-11-20 10:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rpas", "0009_alter_rpastechnicallogparta_log_entry_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Risk category name (e.g., Aircraft Operations, Personnel, Weather)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for category (e.g., AO, PER, WX)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of risk category scope"
                    ),
                ),
                (
                    "casa_reference",
                    models.CharField(
                        blank=True,
                        help_text="CASA SMS manual reference for this category",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Category available for new risk assessments",
                    ),
                ),
                (
                    "default_likelihood_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="AI modifier for likelihood scoring (0.1-2.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "default_consequence_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="AI modifier for consequence scoring (0.1-2.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Risk Category",
                "verbose_name_plural": "Risk Categories",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="RiskRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_number",
                    models.CharField(
                        help_text="Unique risk identifier (auto-generated)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Concise risk title/description", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed risk description and potential consequences"
                    ),
                ),
                (
                    "inherent_likelihood",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Remote - Extremely unlikely to occur"),
                            (2, "Improbable - Unlikely to occur"),
                            (3, "Possible - May occur occasionally"),
                            (4, "Probable - Likely to occur"),
                            (5, "Frequent - Expected to occur regularly"),
                        ],
                        help_text="Inherent likelihood score (before controls)",
                    ),
                ),
                (
                    "inherent_consequence",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Negligible - Minimal impact"),
                            (2, "Minor - Small impact, easily managed"),
                            (3, "Moderate - Noticeable impact, manageable"),
                            (4, "Major - Significant impact, serious concern"),
                            (5, "Catastrophic - Extreme impact, unacceptable"),
                        ],
                        help_text="Inherent consequence score (before controls)",
                    ),
                ),
                (
                    "residual_likelihood",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Remote - Extremely unlikely to occur"),
                            (2, "Improbable - Unlikely to occur"),
                            (3, "Possible - May occur occasionally"),
                            (4, "Probable - Likely to occur"),
                            (5, "Frequent - Expected to occur regularly"),
                        ],
                        help_text="Residual likelihood score (after controls)",
                    ),
                ),
                (
                    "residual_consequence",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Negligible - Minimal impact"),
                            (2, "Minor - Small impact, easily managed"),
                            (3, "Moderate - Noticeable impact, manageable"),
                            (4, "Major - Significant impact, serious concern"),
                            (5, "Catastrophic - Extreme impact, unacceptable"),
                        ],
                        help_text="Residual consequence score (after controls)",
                    ),
                ),
                (
                    "inherent_risk_rating",
                    models.CharField(
                        choices=[
                            ("extreme", "Extreme - Unacceptable Risk"),
                            ("high", "High - Unacceptable Risk"),
                            ("medium", "Medium - Acceptable with Controls"),
                            ("low", "Low - Acceptable Risk"),
                            ("negligible", "Negligible - Minimal Risk"),
                        ],
                        editable=False,
                        help_text="AI-calculated inherent risk rating",
                        max_length=20,
                    ),
                ),
                (
                    "residual_risk_rating",
                    models.CharField(
                        choices=[
                            ("extreme", "Extreme - Unacceptable Risk"),
                            ("high", "High - Unacceptable Risk"),
                            ("medium", "Medium - Acceptable with Controls"),
                            ("low", "Low - Acceptable Risk"),
                            ("negligible", "Negligible - Minimal Risk"),
                        ],
                        editable=False,
                        help_text="AI-calculated residual risk rating",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Under Development"),
                            ("open", "Open - Active Risk"),
                            ("monitoring", "Monitoring - Controls in Place"),
                            ("closed", "Closed - Risk Eliminated"),
                            ("superseded", "Superseded - Replaced by New Assessment"),
                        ],
                        default="draft",
                        help_text="Current status of risk assessment",
                        max_length=20,
                    ),
                ),
                (
                    "identified_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date risk was first identified"
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(help_text="Date of current risk assessment"),
                ),
                (
                    "review_date",
                    models.DateField(help_text="Date for next risk review"),
                ),
                (
                    "auto_review_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable AI-powered automatic review triggers",
                    ),
                ),
                (
                    "f2_integration_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Link risk to F2 maintenance automation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        help_text="Person who conducted risk assessment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessed_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Risk category for classification",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risks",
                        to="sms.riskcategory",
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        help_text="Person who identified this risk",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identified_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="RPAS operator this risk applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="rpas.rpasoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Register Entry",
                "verbose_name_plural": "Risk Register",
                "ordering": ["-assessment_date", "risk_number"],
                "permissions": [
                    ("approve_risk_assessments", "Can approve risk assessments"),
                    ("manage_risk_register", "Can manage risk register"),
                    ("view_risk_analytics", "Can view risk analytics"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StandardOperatingProcedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sop_number",
                    models.CharField(
                        help_text="Unique SOP identifier (auto-generated)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="SOP title", max_length=200)),
                (
                    "sop_type",
                    models.CharField(
                        choices=[
                            ("operational", "Operational Procedure"),
                            ("emergency", "Emergency Procedure"),
                            ("maintenance", "Maintenance Procedure"),
                            ("training", "Training Procedure"),
                            ("administrative", "Administrative Procedure"),
                        ],
                        help_text="Type of procedure",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(help_text="Purpose and scope of this SOP"),
                ),
                (
                    "procedure_content",
                    models.TextField(help_text="Step-by-step procedure content"),
                ),
                (
                    "version_number",
                    models.CharField(
                        default="1.0", help_text="Current version number", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Under Development"),
                            ("review", "Under Review"),
                            ("approved", "Approved - Current"),
                            ("superseded", "Superseded - Replaced"),
                            ("archived", "Archived - Historical"),
                        ],
                        default="draft",
                        help_text="Current status of SOP",
                        max_length=20,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date SOP was created"
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, help_text="Date SOP was approved", null=True
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, help_text="Date SOP becomes effective", null=True
                    ),
                ),
                ("review_date", models.DateField(help_text="Date for next SOP review")),
                (
                    "auto_acknowledgment_tracking",
                    models.BooleanField(
                        default=True,
                        help_text="Track staff acknowledgment automatically",
                    ),
                ),
                (
                    "requires_training",
                    models.BooleanField(
                        default=False,
                        help_text="SOP requires formal training before use",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Key personnel who approved this SOP",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_sops",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Person who authored this SOP",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_sops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="RPAS operator this SOP belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sops",
                        to="rpas.rpasoperator",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who reviewed this SOP",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_sops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Operating Procedure",
                "verbose_name_plural": "Standard Operating Procedures",
                "ordering": ["sop_number", "title"],
                "permissions": [
                    ("approve_sops", "Can approve SOPs"),
                    ("manage_sop_versions", "Can manage SOP versions"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "control_number",
                    models.CharField(
                        help_text="Unique control identifier (auto-generated)",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Control title/name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of control measure"
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("elimination", "Elimination - Remove the hazard"),
                            (
                                "substitution",
                                "Substitution - Replace with safer alternative",
                            ),
                            (
                                "engineering",
                                "Engineering Controls - Physical barriers/systems",
                            ),
                            (
                                "administrative",
                                "Administrative Controls - Procedures/training",
                            ),
                            ("ppe", "Personal Protective Equipment"),
                        ],
                        help_text="Type of control in hierarchy of controls",
                        max_length=20,
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.CharField(
                        choices=[
                            ("very_high", "Very High - 95%+ effective"),
                            ("high", "High - 80-94% effective"),
                            ("medium", "Medium - 60-79% effective"),
                            ("low", "Low - 40-59% effective"),
                            ("very_low", "Very Low - <40% effective"),
                        ],
                        help_text="Estimated effectiveness of this control",
                        max_length=20,
                    ),
                ),
                (
                    "implementation_date",
                    models.DateField(help_text="Date control was implemented"),
                ),
                (
                    "verification_date",
                    models.DateField(
                        blank=True,
                        help_text="Date control effectiveness was last verified",
                        null=True,
                    ),
                ),
                (
                    "next_verification_date",
                    models.DateField(help_text="Date for next control verification"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Control currently in effect"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsible_person",
                    models.ForeignKey(
                        help_text="Person responsible for implementing/maintaining control",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        help_text="Risk this control mitigates",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="sms.riskregister",
                    ),
                ),
                (
                    "linked_sop",
                    models.ForeignKey(
                        blank=True,
                        help_text="SOP that implements this control",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_controls",
                        to="sms.standardoperatingprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Control",
                "verbose_name_plural": "Risk Controls",
                "ordering": ["control_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="SOPAcknowledgment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "acknowledged_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time of acknowledgment"
                    ),
                ),
                (
                    "version_acknowledged",
                    models.CharField(
                        help_text="Version of SOP acknowledged", max_length=10
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Is this acknowledgment for current SOP version?",
                    ),
                ),
                (
                    "acknowledgment_method",
                    models.CharField(
                        default="digital_system",
                        help_text="Method used for acknowledgment",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of acknowledgment for audit trail",
                        null=True,
                    ),
                ),
                (
                    "training_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Required training completed before acknowledgment",
                    ),
                ),
                (
                    "training_completion_date",
                    models.DateField(
                        blank=True, help_text="Date training was completed", null=True
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        help_text="Staff member acknowledging SOP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sop_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sop",
                    models.ForeignKey(
                        help_text="SOP being acknowledged",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="sms.standardoperatingprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOP Acknowledgment",
                "verbose_name_plural": "SOP Acknowledgments",
                "ordering": ["-acknowledged_date"],
                "unique_together": {("sop", "staff_member", "version_acknowledged")},
            },
        ),
    ]
