# Generated by Django 5.2.8 on 2025-11-20 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0009_alter_rpastechnicallogparta_log_entry_number"),
        ("sms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSafetyAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jsa_number",
                    models.CharField(
                        help_text="Unique JSA identifier (auto-generated)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job/task title being analyzed", max_length=200
                    ),
                ),
                (
                    "jsa_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Operation"),
                            ("maintenance", "Maintenance Activity"),
                            ("emergency", "Emergency Procedure"),
                            ("training", "Training Activity"),
                            ("special", "Special Operation"),
                        ],
                        help_text="Type of job being analyzed",
                        max_length=20,
                    ),
                ),
                (
                    "job_description",
                    models.TextField(help_text="Detailed description of the job/task"),
                ),
                (
                    "location_description",
                    models.TextField(help_text="Description of where job is performed"),
                ),
                (
                    "personnel_required",
                    models.TextField(
                        help_text="Personnel required for this job (qualifications, numbers)"
                    ),
                ),
                (
                    "equipment_required",
                    models.TextField(
                        help_text="Equipment, tools, and materials required"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Under Development"),
                            ("review", "Under Review"),
                            ("approved", "Approved - Current"),
                            ("superseded", "Superseded - Replaced"),
                        ],
                        default="draft",
                        help_text="Current status of JSA",
                        max_length=20,
                    ),
                ),
                ("analysis_date", models.DateField(help_text="Date JSA was conducted")),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, help_text="Date JSA was approved", null=True
                    ),
                ),
                ("review_date", models.DateField(help_text="Date for next JSA review")),
                (
                    "auto_risk_linking",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically link JSA hazards to risk register",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        help_text="Person who conducted the JSA",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyzed_jsas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Key personnel who approved this JSA",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_jsas",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="RPAS operator this JSA belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_safety_analyses",
                        to="rpas.rpasoperator",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who reviewed this JSA",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_jsas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Safety Analysis",
                "verbose_name_plural": "Job Safety Analyses",
                "ordering": ["-analysis_date", "jsa_number"],
                "permissions": [
                    ("approve_jsas", "Can approve JSAs"),
                    ("conduct_jsa", "Can conduct job safety analysis"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JSAJobStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_number",
                    models.PositiveSmallIntegerField(
                        help_text="Sequential step number"
                    ),
                ),
                (
                    "step_description",
                    models.TextField(help_text="Detailed description of this job step"),
                ),
                (
                    "estimated_duration",
                    models.DurationField(
                        blank=True,
                        help_text="Estimated time to complete this step",
                        null=True,
                    ),
                ),
                (
                    "is_critical_step",
                    models.BooleanField(
                        default=False, help_text="Is this a safety-critical step?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jsa",
                    models.ForeignKey(
                        help_text="JSA this step belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_steps",
                        to="sms.jobsafetyanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "JSA Job Step",
                "verbose_name_plural": "JSA Job Steps",
                "ordering": ["jsa", "step_number"],
                "unique_together": {("jsa", "step_number")},
            },
        ),
        migrations.CreateModel(
            name="JSAHazard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hazard_description",
                    models.TextField(help_text="Description of the potential hazard"),
                ),
                (
                    "hazard_type",
                    models.CharField(
                        choices=[
                            (
                                "physical",
                                "Physical - Contact with objects, falls, etc.",
                            ),
                            ("chemical", "Chemical - Exposure to substances"),
                            ("biological", "Biological - Exposure to organisms"),
                            ("ergonomic", "Ergonomic - Repetitive motion, posture"),
                            ("psychological", "Psychological - Stress, fatigue"),
                            ("environmental", "Environmental - Weather, terrain"),
                            ("operational", "Operational - Procedures, equipment"),
                        ],
                        help_text="Type/category of hazard",
                        max_length=20,
                    ),
                ),
                (
                    "potential_consequences",
                    models.TextField(
                        help_text="What could happen if this hazard occurs?"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("extreme", "Extreme - Stop work immediately"),
                            ("high", "High - Additional controls required"),
                            ("medium", "Medium - Controls adequate"),
                            ("low", "Low - Monitor and review"),
                            ("negligible", "Negligible - Minimal concern"),
                        ],
                        help_text="Initial risk level assessment",
                        max_length=20,
                    ),
                ),
                (
                    "control_measures",
                    models.TextField(
                        help_text="Control measures to mitigate this hazard"
                    ),
                ),
                (
                    "auto_risk_created",
                    models.BooleanField(
                        default=False,
                        help_text="Was risk register entry auto-created from this hazard?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_risk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked risk register entry (AI-generated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jsa_hazards",
                        to="sms.riskregister",
                    ),
                ),
                (
                    "job_step",
                    models.ForeignKey(
                        help_text="Job step this hazard relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazards",
                        to="sms.jsajobstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "JSA Hazard",
                "verbose_name_plural": "JSA Hazards",
                "ordering": ["job_step", "hazard_type", "risk_level"],
            },
        ),
    ]
