# Generated by Django 5.2.8 on 2025-11-20 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0009_alter_rpastechnicallogparta_log_entry_number"),
        ("sms", "0002_jobsafetyanalysis_jsajobstep_jsahazard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short category code (e.g., 'COLL' for collision)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
                (
                    "description",
                    models.TextField(help_text="Detailed category description"),
                ),
                (
                    "casa_reportable",
                    models.BooleanField(
                        default=False,
                        help_text="Must this category be reported to CASA?",
                    ),
                ),
                (
                    "reporting_timeframe",
                    models.DurationField(
                        blank=True,
                        help_text="Timeframe for reporting to CASA",
                        null=True,
                    ),
                ),
                (
                    "default_severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor - No injury, minor damage"),
                            ("serious", "Serious - Injury or significant damage"),
                            ("major", "Major - Serious injury or major damage"),
                            ("fatal", "Fatal - Fatality or catastrophic damage"),
                        ],
                        default="minor",
                        help_text="Default severity level for this category",
                        max_length=20,
                    ),
                ),
                (
                    "auto_investigation_required",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically trigger investigation for this category?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Category available for selection"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Incident Category",
                "verbose_name_plural": "Incident Categories",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_number",
                    models.CharField(
                        help_text="Unique incident identifier (auto-generated)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief incident title/summary", max_length=200
                    ),
                ),
                (
                    "incident_date",
                    models.DateTimeField(
                        help_text="Date and time when incident occurred"
                    ),
                ),
                ("location", models.TextField(help_text="Where the incident occurred")),
                (
                    "description",
                    models.TextField(help_text="Detailed description of what happened"),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("minor", "Minor - No injury, minor damage"),
                            ("serious", "Serious - Injury or significant damage"),
                            ("major", "Major - Serious injury or major damage"),
                            ("fatal", "Fatal - Fatality or catastrophic damage"),
                        ],
                        help_text="Incident severity assessment",
                        max_length=20,
                    ),
                ),
                (
                    "actual_consequences",
                    models.TextField(
                        help_text="What actually happened - injuries, damage, etc."
                    ),
                ),
                (
                    "potential_consequences",
                    models.TextField(
                        help_text="What could have happened in worst case"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported - Initial report submitted"),
                            ("under_review", "Under Review - Being assessed"),
                            ("investigating", "Investigating - Formal investigation"),
                            (
                                "corrective_actions",
                                "Corrective Actions - Implementing fixes",
                            ),
                            ("closed", "Closed - Investigation complete"),
                        ],
                        default="reported",
                        help_text="Current incident status",
                        max_length=20,
                    ),
                ),
                (
                    "investigation_required",
                    models.BooleanField(
                        default=False,
                        help_text="Does this incident require formal investigation?",
                    ),
                ),
                (
                    "investigation_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Investigation completion deadline",
                        null=True,
                    ),
                ),
                (
                    "casa_reportable",
                    models.BooleanField(
                        default=False,
                        help_text="Must this incident be reported to CASA?",
                    ),
                ),
                (
                    "casa_reported",
                    models.BooleanField(
                        default=False, help_text="Has this been reported to CASA?"
                    ),
                ),
                (
                    "casa_report_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time CASA report was submitted",
                        null=True,
                    ),
                ),
                (
                    "casa_reference",
                    models.CharField(
                        blank=True, help_text="CASA reference number", max_length=50
                    ),
                ),
                (
                    "auto_risk_created",
                    models.BooleanField(
                        default=False, help_text="Was risk register entry auto-created?"
                    ),
                ),
                (
                    "closed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date incident investigation was closed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft_involved",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aircraft involved in incident",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="rpas.rpasaircraft",
                    ),
                ),
                (
                    "investigator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned investigator",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investigated_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "involved_personnel",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Personnel involved in the incident",
                        related_name="involved_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_risk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked risk register entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="sms.riskregister",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="RPAS operator this incident relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="rpas.rpasoperator",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Person who reported the incident",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "similar_incidents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="AI-identified similar incidents",
                        related_name="related_incidents",
                        to="sms.incident",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Incident category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="sms.incidentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-incident_date", "incident_number"],
                "permissions": [
                    ("investigate_incidents", "Can investigate incidents"),
                    ("close_incidents", "Can close incident investigations"),
                    ("report_to_casa", "Can report incidents to CASA"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_number",
                    models.CharField(
                        help_text="Unique action identifier (auto-generated)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief action description", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of required action"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("procedural", "Procedural - Update procedures/SOPs"),
                            ("training", "Training - Additional training required"),
                            ("equipment", "Equipment - Equipment/system changes"),
                            ("administrative", "Administrative - Policy/admin changes"),
                            ("engineering", "Engineering - Design/technical changes"),
                        ],
                        help_text="Type of corrective action",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low - Routine improvement"),
                            ("medium", "Medium - Moderate priority"),
                            ("high", "High - Urgent action required"),
                            ("critical", "Critical - Immediate action required"),
                        ],
                        default="medium",
                        help_text="Action priority level",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(help_text="Target completion date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open - Not started"),
                            ("in_progress", "In Progress - Being implemented"),
                            ("completed", "Completed - Implementation finished"),
                            ("verified", "Verified - Effectiveness confirmed"),
                            ("closed", "Closed - Action complete and effective"),
                        ],
                        default="open",
                        help_text="Current action status",
                        max_length=20,
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True, help_text="Progress updates and notes"
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, help_text="Date action was completed", null=True
                    ),
                ),
                (
                    "verification_date",
                    models.DateField(
                        blank=True,
                        help_text="Date verification was completed",
                        null=True,
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Verification results and notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Person who assigned this action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jsa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source JSA (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="sms.jobsafetyanalysis",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="RPAS operator this action relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="rpas.rpasoperator",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        help_text="Person responsible for implementing action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source risk (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="sms.riskregister",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who verified action effectiveness",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source incident (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="sms.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corrective Action",
                "verbose_name_plural": "Corrective Actions",
                "ordering": ["-created_at", "due_date"],
            },
        ),
    ]
