# Generated by Django 5.2.8 on 2025-11-13 11:04

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="City/town name", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="City center latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="City center longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        blank=True,
                        help_text="City population (for sorting/filtering)",
                        null=True,
                    ),
                ),
                (
                    "is_major_city",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is considered a major city",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this city is available for selection",
                    ),
                ),
            ],
            options={
                "verbose_name": "City/Town",
                "verbose_name_plural": "Cities/Towns",
                "db_table": "core_city",
                "ordering": ["state__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso_code_2",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g., 'AU', 'US')",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "iso_code_3",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 country code (e.g., 'AUS', 'USA')",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full country name", max_length=100, unique=True
                    ),
                ),
                (
                    "official_name",
                    models.CharField(
                        blank=True, help_text="Official country name", max_length=200
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Country center latitude for mapping",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Country center longitude for mapping",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this country is available for selection",
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(
                        blank=True,
                        help_text="International phone code (e.g., '+61')",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "core_country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProfileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("general", "General User"),
                            ("staff", "Staff Member"),
                            ("pilot", "Pilot"),
                            ("client", "Client"),
                            ("customer", "Customer"),
                        ],
                        help_text="Unique code for profile type",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for profile type", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this profile type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this profile type is currently available",
                    ),
                ),
                (
                    "requires_image",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this profile type requires an image",
                    ),
                ),
                (
                    "has_admin_access",
                    models.BooleanField(
                        default=False,
                        help_text="Whether users with this profile can access admin features",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Type",
                "verbose_name_plural": "Profile Types",
                "db_table": "core_profile_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address used for login",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into admin site",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user's email has been verified",
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token used for email verification",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "core_user",
            },
        ),
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text="Postal/ZIP code", max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Postal code area center latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Postal code area center longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of area (urban, suburban, rural, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this postal code is available for selection",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Parent city",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postal_codes",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postal Code",
                "verbose_name_plural": "Postal Codes",
                "db_table": "core_postal_code",
                "ordering": ["city__name", "code"],
                "unique_together": {("city", "code")},
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="State/province code (e.g., 'NSW', 'CA')",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="State/province name", max_length=100),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="State center latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="State center longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this state is available for selection",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Parent country",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "State/Province",
                "verbose_name_plural": "States/Provinces",
                "db_table": "core_state",
                "ordering": ["country__name", "name"],
                "unique_together": {("country", "code")},
            },
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                help_text="Parent state/province",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="core.state",
            ),
        ),
        migrations.CreateModel(
            name="BaseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Profile image (required for staff and pilot profiles)",
                        null=True,
                        upload_to=core.models.profile_image_upload_path,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Primary phone number", max_length=20
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Date of birth (required for staff and pilot profiles)",
                        null=True,
                    ),
                ),
                (
                    "tax_file_number",
                    models.CharField(
                        blank=True,
                        help_text="Tax File Number (required for staff and pilot profiles)",
                        max_length=11,
                    ),
                ),
                (
                    "arn_number",
                    models.CharField(
                        blank=True,
                        help_text="Aviation Reference Number (required for pilot profiles only)",
                        max_length=20,
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Street address line 1", max_length=255
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 2 (apartment, suite, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Precise latitude for mapping (Leaflet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Precise longitude for mapping (Leaflet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief biography or description"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Personal or company website"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this profile has been verified by staff",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this profile is publicly visible",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City (fallback if postal code not available)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles_direct",
                        to="core.city",
                    ),
                ),
                (
                    "postal_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Postal/ZIP code (automatically provides city, state, country)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="core.postalcode",
                    ),
                ),
                (
                    "profile_type",
                    models.ForeignKey(
                        help_text="Type of profile",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.profiletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "core_profile",
                "unique_together": {("user", "profile_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("state", "name")},
        ),
    ]
