# Generated by Django 5.2.8 on 2025-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Country area in square kilometers",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="population",
            field=models.BigIntegerField(
                blank=True, help_text="Country population (for reference)", null=True
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Geographic region (e.g., 'Europe', 'Asia')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="subregion",
            field=models.CharField(
                blank=True,
                help_text="Geographic subregion (e.g., 'Western Europe')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
