# Generated by Django 5.2.8 on 2025-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_country_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="State/province area in square kilometers",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="division_type",
            field=models.CharField(
                blank=True,
                help_text="Type of division (e.g., 'State', 'Province', 'Territory', 'Region')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="iso_code",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-2 subdivision code (if available)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="population",
            field=models.BigIntegerField(
                blank=True, help_text="State/province population", null=True
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(
                help_text="State/province code (e.g., 'NSW', 'CA', 'TX')", max_length=10
            ),
        ),
    ]
