# Generated by Django 5.2.8 on 2025-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_state_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="City area in square kilometers",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="city_type",
            field=models.CharField(
                blank=True,
                help_text="Type of city (e.g., 'Capital', 'Major City', 'Town', 'Borough')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="data_quality",
            field=models.CharField(
                blank=True,
                default="good",
                help_text="Quality of city data (high, good, fair, low)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="data_source",
            field=models.CharField(
                blank=True,
                default="manual",
                help_text="Source of city data (e.g., 'geonames', 'manual', 'census')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="elevation",
            field=models.IntegerField(
                blank=True,
                help_text="City elevation in meters above sea level",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="is_national_capital",
            field=models.BooleanField(
                default=False, help_text="Whether this is a national capital"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="is_state_capital",
            field=models.BooleanField(
                default=False, help_text="Whether this is a state/province capital"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="City timezone (e.g., 'America/New_York')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
