# Generated by Django 5.2.8 on 2025-11-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_city_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseprofile",
            name="postal_code_manual",
            field=models.CharField(
                blank=True,
                help_text="Manual postal/ZIP code entry (when not in database)",
                max_length=20,
                null=True,
            ),
        ),
    ]
