# Generated by Django 5.2.8 on 2025-11-20 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0005_add_postal_code_manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_code",
                    models.CharField(
                        help_text="Unique identifier for this compliance rule (e.g., 'MOS_101_4_02')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        help_text="Human-readable name of the compliance rule",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what this rule checks"
                    ),
                ),
                (
                    "casa_reference",
                    models.CharField(
                        help_text="Official CASA reference (e.g., 'CASA MOS Part 101 Section 4.02')",
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("green", "Compliant"),
                            ("yellow", "Warning"),
                            ("red", "Non-Compliant"),
                        ],
                        default="red",
                        help_text="Default severity level if this rule fails",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rule is currently enforced",
                    ),
                ),
                (
                    "check_frequency_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="How often this rule should be checked (in hours)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Compliance Rule",
                "verbose_name_plural": "Compliance Rules",
                "ordering": ["rule_code"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("green", "Compliant"),
                            ("yellow", "Warning"),
                            ("red", "Non-Compliant"),
                        ],
                        help_text="Current compliance status for this check",
                        max_length=10,
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this compliance check was last performed",
                    ),
                ),
                (
                    "next_check_due",
                    models.DateTimeField(
                        blank=True, help_text="When the next check is due", null=True
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Additional details about the compliance check result",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this compliance check",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="The compliance rule being checked",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.compliancerule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Check",
                "verbose_name_plural": "Compliance Checks",
                "ordering": ["-last_checked"],
                "unique_together": {("content_type", "object_id", "rule")},
            },
        ),
    ]
