# Generated by Django 5.2.8 on 2025-11-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_three_color_compliance_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancerule",
            name="custom_method_name",
            field=models.CharField(
                blank=True,
                help_text="Method name to call on model for custom evaluations (e.g., 'check_maintenance_overdue')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="evaluation_type",
            field=models.CharField(
                choices=[
                    ("date_past", "Date is in the past (expired)"),
                    ("date_future", "Date is in the future"),
                    ("date_within_days", "Date within X days"),
                    ("boolean_true", "Boolean field must be True"),
                    ("boolean_false", "Boolean field must be False"),
                    ("equals", "Field equals specific value"),
                    ("not_equals", "Field does not equal specific value"),
                    ("greater_than", "Numeric field greater than value"),
                    ("less_than", "Numeric field less than value"),
                    ("exists", "Field has a value (not None/empty)"),
                    ("not_exists", "Field is None or empty"),
                    ("related_count", "Count of related objects meets criteria"),
                    ("custom_method", "Call custom method on model"),
                ],
                default="exists",
                help_text="Type of evaluation to perform on the field",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="failure_message",
            field=models.TextField(
                blank=True, help_text="Custom message when rule fails (optional)"
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="field_path",
            field=models.CharField(
                default="id",
                help_text="Field path to evaluate (e.g., 'aircraft.registration_expiry_date', 'status', 'created_date')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="target_app",
            field=models.CharField(
                blank=True,
                help_text="Django app name (e.g., 'rpas', 'sms', 'aviation')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="target_model",
            field=models.CharField(
                blank=True,
                help_text="Model class name this rule applies to (e.g., 'RPASTechnicalLogPartA')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="trigger_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of days for date-based evaluations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="trigger_numeric",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Numeric trigger value for greater_than/less_than comparisons",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="trigger_value",
            field=models.CharField(
                blank=True,
                help_text="Value to compare against (e.g., '30' for days, 'active' for status, 'True' for boolean)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="severity",
            field=models.CharField(
                choices=[
                    ("green", "Compliant"),
                    ("yellow", "Warning"),
                    ("red", "Non-Compliant"),
                ],
                default="red",
                help_text="Severity level if this rule fails",
                max_length=10,
            ),
        ),
    ]
