# Generated by Django 5.2.8 on 2025-11-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_revolutionary_compliance_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green - Compliant"),
                            ("YELLOW", "Yellow - Warning"),
                            ("RED", "Red - Non-Compliant"),
                        ],
                        help_text="Three-color compliance status code",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable status name", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of this compliance status",
                    ),
                ),
                (
                    "priority_level",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Priority level (1=highest, 3=lowest) for status processing",
                    ),
                ),
                (
                    "requires_action",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this status requires user action",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this status is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Compliance Status",
                "verbose_name_plural": "Compliance Statuses",
                "db_table": "core_compliance_status",
                "ordering": ["priority_level", "status_code"],
            },
        ),
        migrations.AlterField(
            model_name="compliancecheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("green", "Green - Compliant"),
                    ("yellow", "Yellow - Warning"),
                    ("red", "Red - Non-Compliant"),
                ],
                help_text="Current compliance status for this check",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="severity",
            field=models.CharField(
                choices=[
                    ("green", "Green - Compliant"),
                    ("yellow", "Yellow - Warning"),
                    ("red", "Red - Non-Compliant"),
                ],
                default="red",
                help_text="Severity level if this rule fails",
                max_length=10,
            ),
        ),
    ]
