# Generated by Django 5.2.8 on 2025-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_compliance_status_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancestatus",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description of this compliance status",
                null=True,
            ),
        ),
    ]
