# Generated by Django 5.2.8 on 2025-11-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_fix_compliance_status_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancerule",
            name="check_frequency_hours",
            field=models.PositiveIntegerField(
                blank=True,
                default=24,
                help_text="How often this rule should be checked (in hours)",
                null=True,
            ),
        ),
    ]
