"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-u&a36_$5)ewjx)0kpc%19iuo$6_ga(#ba&*!6u$^o88-8de1q&",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    # Django Core Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",  # PostGIS support
    # Third-party Apps
    "rest_framework",  # Django REST Framework
    "corsheaders",  # django-cors-headers
    "django_extensions",  # django-extensions
    "debug_toolbar",  # django-debug-toolbar
    "axes",  # django-axes (security)
    "django_celery_beat",  # django-celery-beat
    "crispy_forms",  # django-crispy-forms
    "crispy_bootstrap5",  # crispy-bootstrap5
    "django_cotton",  # django-cotton
    "django_htmx",  # django-htmx
    "guardian",  # django-guardian (object-level permissions)
    "import_export",  # django-import-export
    "django_filters",  # django-filter
    "timezone_field",  # django-timezone-field
    "leaflet",  # django-leaflet for interactive maps
    "tailwind",  # django-tailwind
    # "django_browser_reload",  # Auto-reload for development - disabled for form testing
    "theme",  # Tailwind CSS theme app
    # Local Apps (core app must be first for dependencies)
    "core",  # Core functionality - central hub for all models
    "accounts",  # Authentication and user management
    "aviation",  # Australian airspace and regulatory data (GeoDjango)
    "rpas",  # RPAS (drone) operations and aviation management
    "sms",  # Safety Management System - intelligent risk and safety management
    "flight_operations",  # Flight operations management (CASA compliance automation)
    # "api",  # API endpoints
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # Debug toolbar (must be early)
    "corsheaders.middleware.CorsMiddleware",  # CORS headers (must be early)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "axes.middleware.AxesMiddleware",  # django-axes (after auth middleware)
    "django_htmx.middleware.HtmxMiddleware",  # HTMX support
    # "accounts.middleware.ProfileCompletionMiddleware",  # DISABLED - Accounts app temporarily disabled during UI rebuild
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if provided, otherwise fall back to individual settings
if config("DATABASE_URL", default=None):
    DATABASES = {"default": dj_database_url.parse(config("DATABASE_URL"))}
    # Force PostGIS backend for GeoDjango support
    DATABASES["default"]["ENGINE"] = "django.contrib.gis.db.backends.postgis"
else:
    # Fallback to PostgreSQL with individual settings
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": config("DB_NAME", default="django_project_db"),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default=""),
            "HOST": config("DB_HOST", default="192.168.0.18"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }

# SQLite fallback for testing (when no PostgreSQL available)
if config("USE_SQLITE", default=False, cast=bool):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Australia/Adelaide"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = config("STATIC_ROOT", default=BASE_DIR / "staticfiles")

# Additional locations of static files for development
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "htmlcov",  # Coverage reports served via Django
]

# Static files finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Static files storage
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = config("MEDIA_ROOT", default=BASE_DIR / "media")

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "core.CustomUser"

# Redis Configuration
REDIS_URL = config("REDIS_URL", default="redis://192.168.0.18:6379/0")

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "django_project",
        "VERSION": 1,
    }
}

# Session Configuration (use Redis for sessions)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Celery Configuration
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default=REDIS_URL)
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default=REDIS_URL)
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Email Configuration
EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)

# Security Settings
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# =============================================================================
# THIRD-PARTY APP CONFIGURATIONS
# =============================================================================

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# Django CORS Headers
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://192.168.0.10:3000",  # Beta server React
    "http://192.168.0.9",  # Alpha server
]
CORS_ALLOW_CREDENTIALS = True

# Django Debug Toolbar
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
    "192.168.0.9",  # Alpha server
]

if DEBUG:
    import socket

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [ip[: ip.rfind(".")] + ".1" for ip in ips]

# Django Axes (Security) + Guardian Authentication
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",  # AxesStandaloneBackend should be first
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",  # Guardian object permissions
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # 1 hour
AXES_LOCKOUT_TEMPLATE = "registration/lockout.html"
AXES_LOCKOUT_URL = "/accounts/locked/"
AXES_LOGIN_FAILURE_LIMIT = 5
AXES_LOCK_OUT_AT_FAILURE = True

# Django Crispy Forms with Bootstrap 5
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django Import/Export
IMPORT_EXPORT_USE_TRANSACTIONS = True

# Django Extensions
GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}

# Django Cotton (Template Components)
COTTON_DIR = "cotton"

# =============================================================================
# TAILWIND CSS CONFIGURATION
# =============================================================================

# Tailwind CSS App Name
TAILWIND_APP_NAME = "theme"

# Internal IPs for development (for browser reload)
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
    "192.168.0.9",  # Alpha server IP
]

# NPM Binary Path (django-tailwind will find it automatically)
# NPM_BIN_PATH = "/usr/bin/npm"  # Uncomment if needed

# =============================================================================
# DJANGO-LEAFLET CONFIGURATION
# =============================================================================

# Leaflet Configuration for Aviation Mapping
LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (-25.2744, 133.7751),  # Center of Australia
    "DEFAULT_ZOOM": 5,
    "MIN_ZOOM": 3,
    "MAX_ZOOM": 18,
    "SCALE": "both",
    "ATTRIBUTION_PREFIX": "Powered by django-leaflet",
    "TILES": [
        (
            "OpenStreetMap",
            "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            {
                "attribution": '© <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
                "maxZoom": 18,
            },
        ),
        (
            "Satellite",
            "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
            {
                "attribution": '© <a href="https://www.esri.com/">Esri</a>, DigitalGlobe, GeoEye, Earthstar Geographics',
                "maxZoom": 18,
            },
        ),
    ],
    "PLUGINS": {"forms": {"auto-include": True}},
    "SRID": 4326,  # WGS84 coordinate system for aviation
    "SPATIAL_EXTENT": [
        96.816941,
        -43.740486,
        153.639252,
        -9.142176,
    ],  # Australia bounds
}

# ===============================================================
# DJANGO-GUARDIAN CONFIGURATION (Object-Level Permissions)
# ===============================================================

# Guardian Settings
GUARDIAN_MONKEY_PATCH_USER = False  # Disable monkey patching for better compatibility
GUARDIAN_GET_INIT_ANONYMOUS_USER = "core.utils.get_anonymous_user_instance"
GUARDIAN_RENDER_403 = True
GUARDIAN_TEMPLATE_403 = "403.html"

# Anonymous user for guardian (required for object permissions)
ANONYMOUS_USER_NAME = "AnonymousUser"
