# Generated by Django 5.2.8 on 2025-11-18 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration",
                    models.CharField(
                        help_text="Aircraft registration number (e.g., VH-ABC123 or internal fleet number)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "make",
                    models.CharField(help_text="Aircraft manufacturer", max_length=100),
                ),
                ("model", models.CharField(help_text="Aircraft model", max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Manufacturer serial number", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Aircraft is operational and available"
                    ),
                ),
                (
                    "is_maintenance",
                    models.BooleanField(
                        default=False, help_text="Aircraft is in maintenance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Legal owner or operator of the aircraft",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_aircraft",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aircraft",
                "verbose_name_plural": "Aircraft",
                "ordering": ["registration"],
                "permissions": [
                    ("operate_aircraft", "Can operate this aircraft"),
                    ("maintain_aircraft", "Can perform maintenance on this aircraft"),
                    ("inspect_aircraft", "Can perform inspections on this aircraft"),
                    ("view_aircraft_logs", "Can view flight logs for this aircraft"),
                    ("manage_aircraft_access", "Can assign pilots to this aircraft"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FlightLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(
                        help_text="Internal flight operation number", max_length=50
                    ),
                ),
                ("flight_date", models.DateField(help_text="Date of flight operation")),
                ("takeoff_time", models.DateTimeField(help_text="Takeoff time")),
                (
                    "landing_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Landing time (null if flight in progress)",
                        null=True,
                    ),
                ),
                (
                    "flight_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total flight duration in minutes",
                        null=True,
                    ),
                ),
                ("purpose", models.TextField(help_text="Purpose of flight operation")),
                (
                    "location",
                    models.CharField(
                        help_text="Flight location/area of operation", max_length=200
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Flight operation completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        help_text="Aircraft used for this flight",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_logs",
                        to="rpas.aircraft",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        help_text="Pilot in command of this flight",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pilot_flight_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Log",
                "verbose_name_plural": "Flight Logs",
                "ordering": ["-flight_date", "-takeoff_time"],
                "permissions": [
                    ("view_flight_log", "Can view this flight log"),
                    ("edit_flight_log", "Can edit this flight log"),
                    ("approve_flight_log", "Can approve this flight log"),
                    ("access_flight_data", "Can access detailed flight data"),
                ],
            },
        ),
    ]
