# Generated by Django 5.2.8 on 2025-11-18 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RPASAircraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration",
                    models.CharField(
                        help_text="Aircraft registration number (VH-XXX or fleet number)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "make",
                    models.CharField(help_text="Aircraft manufacturer", max_length=100),
                ),
                ("model", models.CharField(help_text="Aircraft model", max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Manufacturer serial number", max_length=100
                    ),
                ),
                (
                    "maximum_takeoff_weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Maximum takeoff weight in kg",
                        max_digits=8,
                    ),
                ),
                (
                    "operating_category",
                    models.CharField(
                        help_text="CASA operating category (e.g., Multi-rotor, Fixed-wing)",
                        max_length=50,
                    ),
                ),
                (
                    "is_serviceable",
                    models.BooleanField(
                        default=True, help_text="Aircraft is serviceable"
                    ),
                ),
                (
                    "is_maintenance",
                    models.BooleanField(
                        default=False, help_text="Aircraft in maintenance"
                    ),
                ),
                (
                    "current_flight_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Total flight hours",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RPAS Aircraft",
                "verbose_name_plural": "RPAS Aircraft",
                "ordering": ["operator__company_name", "registration"],
                "permissions": [
                    ("operate_aircraft", "Can operate this aircraft"),
                    ("maintain_aircraft", "Can perform maintenance on this aircraft"),
                    ("inspect_aircraft", "Can perform inspections on this aircraft"),
                    ("authorize_pilots", "Can authorize pilots for this aircraft"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RPASOperator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(help_text="Legal company name", max_length=200),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True,
                        help_text="Trading name if different from legal name",
                        max_length=200,
                    ),
                ),
                (
                    "abn",
                    models.CharField(
                        help_text="Australian Business Number",
                        max_length=11,
                        unique=True,
                    ),
                ),
                (
                    "reoc_number",
                    models.CharField(
                        help_text="CASA Remote Operator Certificate number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("reoc_issue_date", models.DateField(help_text="Date ReOC was issued")),
                ("reoc_expiry_date", models.DateField(help_text="Date ReOC expires")),
                (
                    "physical_address",
                    models.TextField(help_text="Physical business address"),
                ),
                (
                    "postal_address",
                    models.TextField(
                        blank=True,
                        help_text="Postal address if different from physical",
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary contact phone", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Operator is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RPAS Operator",
                "verbose_name_plural": "RPAS Operators",
                "permissions": [
                    ("manage_reoc", "Can manage ReOC certification"),
                    ("view_operator_records", "Can view operator records"),
                    ("audit_operator", "Can perform operator audits"),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="aircraft",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="pilot",
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled Maintenance"),
                            ("unscheduled", "Unscheduled Maintenance"),
                            ("defect_rectification", "Defect Rectification"),
                            ("inspection", "Inspection"),
                            ("modification", "Modification"),
                        ],
                        help_text="Type of maintenance being performed",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of work performed"
                    ),
                ),
                (
                    "defect_description",
                    models.TextField(
                        blank=True, help_text="Description of defect if applicable"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("deferred", "Deferred"),
                        ],
                        default="open",
                        help_text="Current status of maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(help_text="Date maintenance was scheduled"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date maintenance was completed",
                        null=True,
                    ),
                ),
                (
                    "aircraft_hours_at_maintenance",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Aircraft total hours when maintenance performed",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        help_text="Maintenance controller who authorized the work",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorized_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="Person who performed the maintenance",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        help_text="Aircraft this maintenance applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="rpas.rpasaircraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "ordering": ["-scheduled_date", "-created_at"],
                "permissions": [
                    ("authorize_maintenance", "Can authorize maintenance"),
                    ("perform_maintenance", "Can perform maintenance"),
                    ("view_maintenance_records", "Can view maintenance records"),
                ],
            },
        ),
        migrations.AddField(
            model_name="rpasaircraft",
            name="operator",
            field=models.ForeignKey(
                help_text="Company that owns this aircraft (ReOC holder)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft",
                to="rpas.rpasoperator",
            ),
        ),
        migrations.CreateModel(
            name="KeyPersonnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("accountable_manager", "Accountable Manager"),
                            ("maintenance_controller", "Maintenance Controller"),
                            ("safety_officer", "Safety Officer"),
                            ("training_manager", "Training Manager"),
                            ("operations_manager", "Operations Manager"),
                        ],
                        help_text="Key personnel role as per CASA requirements",
                        max_length=30,
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(help_text="Date appointed to this role"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Currently in this role"
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="Relevant qualifications and experience for this role"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="System user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_personnel_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="RPAS operator this person works for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_personnel",
                        to="rpas.rpasoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key Personnel",
                "verbose_name_plural": "Key Personnel",
                "permissions": [
                    ("assign_personnel_roles", "Can assign key personnel roles"),
                    ("view_personnel_records", "Can view personnel records"),
                ],
                "unique_together": {("operator", "user", "role")},
            },
        ),
        migrations.DeleteModel(
            name="Aircraft",
        ),
        migrations.DeleteModel(
            name="FlightLog",
        ),
    ]
