# Generated by Django 5.2.8 on 2025-11-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_postal_code_manual"),
        ("rpas", "0002_rpasaircraft_rpasoperator_remove_flightlog_aircraft_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rpasoperator",
            name="physical_address",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_address",
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="physical_city",
            field=models.ForeignKey(
                help_text="Physical address city",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_physical",
                to="core.city",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="physical_country",
            field=models.ForeignKey(
                help_text="Physical address country",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_physical",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="physical_postal_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical address postal code (optional if not in database)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_physical",
                to="core.postalcode",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="physical_postal_code_manual",
            field=models.CharField(
                blank=True,
                help_text="Manual postal code entry if not in database",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="physical_state",
            field=models.ForeignKey(
                help_text="Physical address state/territory",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_physical",
                to="core.state",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="physical_street_address",
            field=models.CharField(
                blank=True,
                help_text="Physical street address (number, street name)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="postal_city",
            field=models.ForeignKey(
                blank=True,
                help_text="Postal address city (if different from physical)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_postal",
                to="core.city",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="postal_country",
            field=models.ForeignKey(
                blank=True,
                help_text="Postal address country (if different from physical)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_postal",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="postal_postal_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Postal address postal code (if different from physical)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_postal",
                to="core.postalcode",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="postal_postal_code_manual",
            field=models.CharField(
                blank=True,
                help_text="Manual postal code entry if not in database (postal address)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="postal_same_as_physical",
            field=models.BooleanField(
                default=True,
                help_text="Check if postal address is same as physical address",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="postal_state",
            field=models.ForeignKey(
                blank=True,
                help_text="Postal address state/territory (if different from physical)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_postal",
                to="core.state",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="postal_street_address",
            field=models.CharField(
                blank=True,
                help_text="Postal street address (if different from physical)",
                max_length=255,
            ),
        ),
    ]
