# Generated by Django 5.2.8 on 2025-11-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_postal_code_manual"),
        ("rpas", "0003_add_geographical_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpasoperator",
            name="physical_city",
            field=models.ForeignKey(
                help_text="Physical address city",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_physical",
                to="core.city",
            ),
        ),
        migrations.AlterField(
            model_name="rpasoperator",
            name="physical_country",
            field=models.ForeignKey(
                help_text="Physical address country",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_physical",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="rpasoperator",
            name="physical_state",
            field=models.ForeignKey(
                help_text="Physical address state/territory",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_physical",
                to="core.state",
            ),
        ),
        migrations.AlterField(
            model_name="rpasoperator",
            name="physical_street_address",
            field=models.CharField(
                help_text="Physical street address (number, street name)",
                max_length=255,
            ),
        ),
    ]
