# Generated by Django 5.2.8 on 2025-11-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_postal_code_manual"),
        ("rpas", "0004_finalize_address_fields_requirements"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rpasaircraft",
            options={
                "ordering": ["operator__name_of_legal_entity", "registration"],
                "permissions": [
                    ("operate_aircraft", "Can operate this aircraft"),
                    ("maintain_aircraft", "Can perform maintenance on this aircraft"),
                    ("inspect_aircraft", "Can perform inspections on this aircraft"),
                    ("authorize_pilots", "Can authorize pilots for this aircraft"),
                ],
                "verbose_name": "RPAS Aircraft",
                "verbose_name_plural": "RPAS Aircraft",
            },
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="email",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="physical_city",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="physical_country",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="physical_postal_code",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="physical_postal_code_manual",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="physical_state",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="physical_street_address",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_city",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_country",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_postal_code",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_postal_code_manual",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_same_as_physical",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_state",
        ),
        migrations.RemoveField(
            model_name="rpasoperator",
            name="postal_street_address",
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="arn",
            field=models.CharField(
                blank=True,
                help_text="Aviation Reference Number (CASA Table 1)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="name_of_legal_entity",
            field=models.CharField(
                blank=True,
                help_text="Name of legal entity (CASA Table 1)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_city",
            field=models.ForeignKey(
                help_text="Operational headquarters address city (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_operational",
                to="core.city",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_country",
            field=models.ForeignKey(
                help_text="Operational headquarters address country (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_operational",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_phone",
            field=models.CharField(
                blank=True,
                help_text="Operational headquarters phone (CASA Table 1)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_postal_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Operational headquarters postal code (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_operational",
                to="core.postalcode",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_postal_code_manual",
            field=models.CharField(
                blank=True,
                help_text="Manual postal code for operational HQ if not in database",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_state",
            field=models.ForeignKey(
                help_text="Operational headquarters address state/territory (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_operational",
                to="core.state",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_street_address",
            field=models.CharField(
                blank=True,
                help_text="Operational headquarters street address (CASA Table 1)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="registered_office_city",
            field=models.ForeignKey(
                help_text="Registered office address city (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_registered",
                to="core.city",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="registered_office_country",
            field=models.ForeignKey(
                help_text="Registered office address country (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_registered",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="registered_office_postal_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Registered office postal code (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_registered",
                to="core.postalcode",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="registered_office_postal_code_manual",
            field=models.CharField(
                blank=True,
                help_text="Manual postal code for registered office if not in database",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="registered_office_state",
            field=models.ForeignKey(
                help_text="Registered office address state/territory (CASA Table 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rpas_operators_registered",
                to="core.state",
            ),
        ),
        migrations.AddField(
            model_name="rpasoperator",
            name="registered_office_street_address",
            field=models.CharField(
                blank=True,
                help_text="Registered office street address (CASA Table 1)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rpasoperator",
            name="abn",
            field=models.CharField(
                help_text="Australian Business Number (CASA Table 1)",
                max_length=11,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rpasoperator",
            name="trading_name",
            field=models.CharField(
                blank=True, help_text="Trading name (CASA Table 1)", max_length=200
            ),
        ),
    ]
