# Generated by Django 5.2.8 on 2025-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0005_casa_table_1_compliance_step1"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpasoperator",
            name="operational_hq_email",
            field=models.EmailField(
                blank=True,
                help_text="Operational headquarters email (CASA Table 1)",
                max_length=254,
            ),
        ),
    ]
