# Generated by Django 5.2.8 on 2025-11-19 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0006_add_operational_hq_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="keypersonnel",
            unique_together={("operator", "user", "role")},
        ),
        migrations.AddField(
            model_name="keypersonnel",
            name="casa_approved_date",
            field=models.DateField(
                help_text="CASA Table 2: Date approved by CASA for this position",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keypersonnel",
            name="nominated_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chief_remote_pilot", "Chief remote pilot"),
                    ("maintenance_controller", "Maintenance controller"),
                    ("ceo", "CEO"),
                ],
                help_text="CASA Table 2: Nominated position (Chief remote pilot, Maintenance controller, CEO)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="keypersonnel",
            name="appointment_date",
            field=models.DateField(
                help_text="Internal appointment date (before CASA approval)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="keypersonnel",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Legacy role field - being migrated to nominated_position",
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="keypersonnel",
            unique_together={
                ("operator", "user", "nominated_position"),
                ("operator", "user", "role"),
            },
        ),
    ]
