# Generated by Django 5.2.8 on 2025-11-20 01:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0007_alter_keypersonnel_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rpasaircraft",
            options={
                "ordering": ["operator__name_of_legal_entity", "make", "model"],
                "permissions": [
                    ("operate_aircraft", "Can operate this aircraft"),
                    ("maintain_aircraft", "Can perform maintenance on this aircraft"),
                    ("inspect_aircraft", "Can perform inspections on this aircraft"),
                    ("authorize_pilots", "Can authorize pilots for this aircraft"),
                ],
                "verbose_name": "RPAS Aircraft",
                "verbose_name_plural": "RPAS Aircraft",
            },
        ),
        migrations.RemoveField(
            model_name="rpasaircraft",
            name="registration",
        ),
        migrations.AddField(
            model_name="rpasaircraft",
            name="minimum_gross_weight",
            field=models.DecimalField(
                decimal_places=3,
                default=2,
                help_text="Minimum gross weight in kg",
                max_digits=8,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rpasaircraft",
            name="current_flight_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                editable=False,
                help_text="Total flight hours - calculated from flight logs",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="AircraftRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Aircraft registration number (VH-XXX format)",
                        max_length=20,
                    ),
                ),
                (
                    "date_first_registered",
                    models.DateField(
                        help_text="Date aircraft was first registered (audit trail base)"
                    ),
                ),
                (
                    "current_registration_date",
                    models.DateField(
                        help_text="Date of current/most recent registration"
                    ),
                ),
                (
                    "current_registration_expiry",
                    models.DateField(
                        help_text="Date current registration expires (auto-calculated +12 months)"
                    ),
                ),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("current", "Current - Valid Registration"),
                            ("expired", "Expired - Invalid for Operations"),
                            ("pending_renewal", "Pending Renewal - Expiring Soon"),
                            ("suspended", "Suspended - CASA Action"),
                            ("cancelled", "Cancelled - No Longer Valid"),
                            ("historical", "Historical - Replaced Registration"),
                        ],
                        default="current",
                        help_text="Current status of aircraft registration",
                        max_length=20,
                    ),
                ),
                (
                    "is_current_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the current active registration?",
                    ),
                ),
                (
                    "casa_certificate_number",
                    models.CharField(
                        help_text="CASA registration certificate number", max_length=50
                    ),
                ),
                (
                    "casa_registration_category",
                    models.CharField(
                        help_text="CASA aircraft category (RPAS, etc.)", max_length=50
                    ),
                ),
                (
                    "renewal_notification_sent",
                    models.BooleanField(
                        default=False, help_text="Has expiry notification been sent?"
                    ),
                ),
                (
                    "renewal_notification_date",
                    models.DateField(
                        blank=True,
                        help_text="Date expiry notification was sent",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        help_text="Aircraft this registration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="rpas.rpasaircraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aircraft Registration",
                "verbose_name_plural": "Aircraft Registrations",
                "ordering": ["-current_registration_date", "-created_at"],
                "unique_together": {("aircraft", "current_registration_date")},
            },
        ),
        migrations.CreateModel(
            name="F2MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aircraft_model",
                    models.CharField(
                        help_text="Aircraft model this schedule applies to (e.g., 'DJI Matrice 300', 'All Models', 'Custom')",
                        max_length=100,
                    ),
                ),
                (
                    "schedule_name",
                    models.CharField(
                        help_text="Descriptive name for this maintenance schedule",
                        max_length=200,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar-Based (30/60/90 days)"),
                            ("flight_hours", "Flight Hours-Based (25/50/100 hrs)"),
                            ("cyclical", "Cyclical (Pre-flight, Daily, Weekly)"),
                            (
                                "conditional",
                                "Conditional (Weather, Incident, Hard Landing)",
                            ),
                            ("manufacturer", "Manufacturer-Specific Schedule"),
                            ("operational", "Operational Requirements"),
                        ],
                        help_text="Type of maintenance scheduling trigger",
                        max_length=20,
                    ),
                ),
                (
                    "maintenance_item",
                    models.TextField(
                        help_text="Description of maintenance item/task to be performed"
                    ),
                ),
                (
                    "maintenance_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Detailed instructions for completing this maintenance",
                    ),
                ),
                (
                    "calendar_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For calendar-based: Number of days between maintenance (e.g., 30, 60, 90)",
                        null=True,
                    ),
                ),
                (
                    "flight_hours_interval",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For flight hours-based: Hours between maintenance (e.g., 25.0, 50.0, 100.0)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "auto_generate_required",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically generate F2MaintenanceRequired entries when triggered",
                    ),
                ),
                (
                    "advance_notice_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days before maintenance due to generate requirement (for planning)",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Grounds Aircraft"),
                            ("high", "High - Complete Within 24hrs"),
                            ("medium", "Medium - Complete Within Week"),
                            ("low", "Low - Complete When Convenient"),
                            ("routine", "Routine - Scheduled Maintenance"),
                        ],
                        default="routine",
                        help_text="Priority level for generated maintenance requirements",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Schedule is active and will generate maintenance requirements",
                    ),
                ),
                (
                    "manufacturer_schedule",
                    models.BooleanField(
                        default=False,
                        help_text="This is a manufacturer-specified maintenance schedule",
                    ),
                ),
                (
                    "operational_override",
                    models.BooleanField(
                        default=False,
                        help_text="Operational requirement beyond manufacturer specifications",
                    ),
                ),
                (
                    "total_generated_items",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of maintenance items generated by this schedule",
                    ),
                ),
                (
                    "last_generated_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this schedule generated a maintenance requirement",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        help_text="Specific aircraft this maintenance schedule applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_schedules",
                        to="rpas.rpasaircraft",
                    ),
                ),
            ],
            options={
                "ordering": ["aircraft_model", "schedule_type", "priority"],
                "unique_together": {("aircraft_model", "schedule_name")},
            },
        ),
        migrations.CreateModel(
            name="RPASTechnicalLogPartA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "log_entry_number",
                    models.CharField(
                        help_text="Sequential log entry number (auto-generated)",
                        max_length=20,
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date this log entry was created"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        help_text="RPAS aircraft this entry applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_log_entries",
                        to="rpas.rpasaircraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "F2 Technical Log - Part A",
                "verbose_name_plural": "F2 Technical Log - Part A Entries",
                "ordering": ["-entry_date", "-log_entry_number"],
                "unique_together": {("aircraft", "log_entry_number")},
            },
        ),
        migrations.CreateModel(
            name="F2Part101MOSCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "issued_on",
                    models.DateField(
                        auto_now_add=True, help_text="Date MOS certification was issued"
                    ),
                ),
                (
                    "signed_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when certification was digitally signed",
                    ),
                ),
                (
                    "signature_method",
                    models.CharField(
                        default="digital_authorization",
                        help_text="Method used for signature (digital_authorization, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "signature_reference",
                    models.CharField(
                        blank=True,
                        help_text="Digital signature reference or hash",
                        max_length=100,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the current valid MOS certification?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="KeyPersonnel authorized to issue MOS certifications (MC, CRP, CEO)",
                        limit_choices_to={"is_current": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_mos_certifications",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "f2_header",
                    models.ForeignKey(
                        help_text="F2 Part A header with auto-populated aircraft data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mos_certifications",
                        to="rpas.rpastechnicallogparta",
                    ),
                ),
            ],
            options={
                "verbose_name": "F2 Part 101 MOS Certification",
                "verbose_name_plural": "F2 Part 101 MOS Certifications",
                "ordering": ["-issued_on", "-signed_datetime"],
                "unique_together": {("f2_header", "issued_on")},
            },
        ),
        migrations.CreateModel(
            name="F2MinorDefects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item",
                    models.TextField(
                        help_text="Description of minor defect requiring monitoring"
                    ),
                ),
                (
                    "found_date",
                    models.DateField(help_text="Date defect was found (required)"),
                ),
                (
                    "found_by_name",
                    models.CharField(
                        help_text="Full name of person who found defect (required)",
                        max_length=200,
                    ),
                ),
                (
                    "found_by_arn",
                    models.CharField(
                        help_text="ARN of person who found defect (required)",
                        max_length=20,
                    ),
                ),
                (
                    "rectified_date",
                    models.DateField(
                        blank=True,
                        help_text="Date defect was rectified (required to remove from checklist)",
                        null=True,
                    ),
                ),
                (
                    "rectified_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of person who rectified defect (required to remove from checklist)",
                        max_length=200,
                    ),
                ),
                (
                    "rectified_by_arn",
                    models.CharField(
                        blank=True,
                        help_text="ARN of person who rectified defect (required to remove from checklist)",
                        max_length=20,
                    ),
                ),
                (
                    "is_rectified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this minor defect been rectified? (Removes from pre-flight checklist)",
                    ),
                ),
                (
                    "requires_daily_check",
                    models.BooleanField(
                        default=True,
                        help_text="Must this defect be checked during daily inspection?",
                    ),
                ),
                (
                    "monitoring_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Specific instructions for monitoring this defect during pre-flight",
                    ),
                ),
                (
                    "defect_severity",
                    models.CharField(
                        choices=[
                            ("cosmetic", "Cosmetic - No Safety Impact"),
                            ("minor", "Minor - Monitor During Flight"),
                            ("wear", "Normal Wear - Schedule Replacement"),
                            ("operational", "Operational - Monitor Performance"),
                        ],
                        default="minor",
                        help_text="Severity level of minor defect",
                        max_length=20,
                    ),
                ),
                (
                    "rectification_method",
                    models.TextField(
                        blank=True, help_text="Description of how defect was rectified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "found_by_personnel",
                    models.ForeignKey(
                        blank=True,
                        help_text="KeyPersonnel who found defect (if in system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="found_minor_defects",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "rectified_by_personnel",
                    models.ForeignKey(
                        blank=True,
                        help_text="KeyPersonnel who rectified defect (if in system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rectified_minor_defects",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "f2_header",
                    models.ForeignKey(
                        help_text="F2 Part A header with auto-populated aircraft data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minor_defects",
                        to="rpas.rpastechnicallogparta",
                    ),
                ),
            ],
            options={
                "verbose_name": "F2 Minor Defect",
                "verbose_name_plural": "F2 Minor Defects",
                "ordering": ["-found_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="F2MajorDefects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item",
                    models.TextField(
                        help_text="Description of major defect that precludes flight"
                    ),
                ),
                (
                    "found_date",
                    models.DateField(help_text="Date defect was found (required)"),
                ),
                (
                    "found_by_name",
                    models.CharField(
                        help_text="Full name of person who found defect (required)",
                        max_length=200,
                    ),
                ),
                (
                    "found_by_arn",
                    models.CharField(
                        help_text="ARN of person who found defect (required)",
                        max_length=20,
                    ),
                ),
                (
                    "rectified_date",
                    models.DateField(
                        blank=True,
                        help_text="Date defect was rectified (required for return to service)",
                        null=True,
                    ),
                ),
                (
                    "rectified_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of person who rectified defect (required for return to service)",
                        max_length=200,
                    ),
                ),
                (
                    "rectified_by_arn",
                    models.CharField(
                        blank=True,
                        help_text="ARN of person who rectified defect (required for return to service)",
                        max_length=20,
                    ),
                ),
                (
                    "is_rectified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this major defect been rectified? (Aircraft grounded until True)",
                    ),
                ),
                (
                    "defect_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Immediate Safety Risk"),
                            ("major", "Major - Flight Safety Affected"),
                            ("structural", "Structural - Aircraft Integrity"),
                            ("system", "System - Key Component Failure"),
                        ],
                        default="major",
                        help_text="Severity level of major defect",
                        max_length=20,
                    ),
                ),
                (
                    "rectification_method",
                    models.TextField(
                        blank=True, help_text="Description of how defect was rectified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "found_by_personnel",
                    models.ForeignKey(
                        blank=True,
                        help_text="KeyPersonnel who found defect (if in system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="found_major_defects",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "rectified_by_personnel",
                    models.ForeignKey(
                        blank=True,
                        help_text="KeyPersonnel who rectified defect (if in system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rectified_major_defects",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "f2_header",
                    models.ForeignKey(
                        help_text="F2 Part A header with auto-populated aircraft data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="major_defects",
                        to="rpas.rpastechnicallogparta",
                    ),
                ),
            ],
            options={
                "verbose_name": "F2 Major Defect",
                "verbose_name_plural": "F2 Major Defects",
                "ordering": ["-found_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="F2MaintenanceRequired",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item",
                    models.TextField(
                        help_text="Description of maintenance item/requirement"
                    ),
                ),
                (
                    "due",
                    models.DateField(
                        help_text="Date maintenance is due to be completed"
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date maintenance was completed (required for completion)",
                        null=True,
                    ),
                ),
                (
                    "completed_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of person who completed maintenance (required for completion)",
                        max_length=200,
                    ),
                ),
                (
                    "completed_by_arn",
                    models.CharField(
                        blank=True,
                        help_text="ARN of person who completed maintenance (required for completion)",
                        max_length=20,
                    ),
                ),
                (
                    "is_overdue",
                    models.BooleanField(
                        default=False, help_text="Is this maintenance item overdue?"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Has this maintenance been completed and validated?",
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Ground Aircraft"),
                            ("high", "High - Complete ASAP"),
                            ("normal", "Normal - Complete by Due Date"),
                            ("low", "Low - Schedule Convenient Time"),
                        ],
                        default="normal",
                        help_text="Priority level of maintenance requirement",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by_personnel",
                    models.ForeignKey(
                        blank=True,
                        help_text="KeyPersonnel who completed maintenance (if in system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_maintenance_items",
                        to="rpas.keypersonnel",
                    ),
                ),
                (
                    "f2_header",
                    models.ForeignKey(
                        help_text="F2 Part A header with auto-populated aircraft data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requirements",
                        to="rpas.rpastechnicallogparta",
                    ),
                ),
            ],
            options={
                "verbose_name": "F2 Maintenance Required",
                "verbose_name_plural": "F2 Maintenance Required",
                "ordering": ["due", "-priority_level", "item"],
            },
        ),
        migrations.DeleteModel(
            name="MaintenanceRecord",
        ),
    ]
