# Generated by Django 5.2.8 on 2025-11-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0008_alter_rpasaircraft_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpastechnicallogparta",
            name="log_entry_number",
            field=models.CharField(
                help_text="Sequential log entry number (auto-generated)", max_length=50
            ),
        ),
    ]
