# Generated by Django 5.2.8 on 2025-11-25 01:43

import rpas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpas", "0009_alter_rpastechnicallogparta_log_entry_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="f2part101moscertification",
            name="issued_on",
            field=models.DateField(
                default=rpas.models.get_current_date,
                help_text="Date MOS certification was issued",
            ),
        ),
    ]
