# Generated by Django 5.2.8 on 2025-11-20 12:26

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_add_postal_code_manual"),
        ("rpas", "0009_alter_rpastechnicallogparta_log_entry_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aerodrome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official aerodrome name", max_length=200
                    ),
                ),
                (
                    "icao_code",
                    models.CharField(
                        blank=True,
                        help_text="4-letter ICAO airport code (if assigned)",
                        max_length=4,
                        unique=True,
                    ),
                ),
                (
                    "iata_code",
                    models.CharField(
                        blank=True,
                        help_text="3-letter IATA airport code (if assigned)",
                        max_length=3,
                    ),
                ),
                (
                    "aerodrome_type",
                    models.CharField(
                        choices=[
                            ("controlled", "Controlled Airport - Tower Operations"),
                            ("uncontrolled", "Uncontrolled Aerodrome"),
                            ("private", "Private Airstrip"),
                            ("heliport", "Heliport"),
                            ("emergency", "Emergency Landing Area"),
                        ],
                        help_text="Type of aerodrome facility",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Aerodrome reference point (ARP)", srid=4326
                    ),
                ),
                (
                    "elevation_ft",
                    models.IntegerField(help_text="Aerodrome elevation in feet AMSL"),
                ),
                (
                    "rpas_no_fly_radius_m",
                    models.IntegerField(
                        default=5500, help_text="RPAS no-fly radius in meters"
                    ),
                ),
                (
                    "tower_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Tower/CTAF frequency (MHz)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is aerodrome currently operational?"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Operational remarks and notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Nearest city",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aerodromes",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aerodrome",
                "verbose_name_plural": "Aerodromes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AirspaceClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official airspace name/identifier", max_length=200
                    ),
                ),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("A", "Class A - Above 18,000ft (IFR only)"),
                            ("C", "Class C - Major Airport Control Zone"),
                            ("D", "Class D - Regional Airport Control Zone"),
                            ("E", "Class E - Controlled Airspace"),
                            ("G", "Class G - Uncontrolled Airspace"),
                            ("R", "Restricted Area - Military/Special Use"),
                            ("P", "Prohibited Area - No Entry"),
                        ],
                        help_text="Australian airspace classification",
                        max_length=1,
                    ),
                ),
                (
                    "icao_designator",
                    models.CharField(
                        blank=True,
                        help_text="ICAO airport/facility designator if applicable",
                        max_length=10,
                    ),
                ),
                (
                    "floor_altitude_ft",
                    models.IntegerField(help_text="Airspace floor in feet AMSL"),
                ),
                (
                    "ceiling_altitude_ft",
                    models.IntegerField(
                        blank=True,
                        help_text="Airspace ceiling in feet AMSL (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Airspace boundary geometry", srid=4326
                    ),
                ),
                (
                    "rpas_access_level",
                    models.CharField(
                        choices=[
                            ("prohibited", "Prohibited - No RPAS access"),
                            ("restricted", "Restricted - Authorization required"),
                            ("controlled", "Controlled - ATC coordination required"),
                            ("unrestricted", "Unrestricted - Standard operations"),
                        ],
                        default="unrestricted",
                        help_text="RPAS access restrictions",
                        max_length=20,
                    ),
                ),
                (
                    "max_rpas_altitude_agl",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum RPAS altitude in feet AGL (if restricted)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(400),
                        ],
                    ),
                ),
                (
                    "authorization_required",
                    models.BooleanField(
                        default=False,
                        help_text="Is CASA authorization required for RPAS operations?",
                    ),
                ),
                (
                    "controlling_authority",
                    models.CharField(
                        blank=True,
                        help_text="ATC facility or controlling authority",
                        max_length=100,
                    ),
                ),
                (
                    "primary_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Primary radio frequency (MHz)",
                        max_length=10,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date airspace becomes effective",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date airspace expires (null = permanent)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this airspace currently active?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional operational notes and restrictions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Airspace Class",
                "verbose_name_plural": "Airspace Classes",
                "ordering": ["class_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["class_type"], name="aviation_ai_class_t_4263d3_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="aviation_ai_is_acti_897478_idx"
                    ),
                    models.Index(
                        fields=["effective_date"], name="aviation_ai_effecti_9e0383_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RPASOperationalZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Operational zone name", max_length=200),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("approved", "Pre-approved Operational Area"),
                            ("standard", "Standard Operations Zone"),
                            ("restricted", "Restricted Operations Zone"),
                            ("training", "Training Area"),
                            ("emergency", "Emergency Response Zone"),
                        ],
                        help_text="Type of operational zone",
                        max_length=20,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Operational zone boundary", srid=4326
                    ),
                ),
                (
                    "max_altitude_agl_ft",
                    models.IntegerField(
                        default=400,
                        help_text="Maximum altitude in feet AGL",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(400),
                        ],
                    ),
                ),
                (
                    "casa_approval_reference",
                    models.CharField(
                        blank=True,
                        help_text="CASA approval reference number",
                        max_length=50,
                    ),
                ),
                (
                    "approval_expiry_date",
                    models.DateField(
                        blank=True, help_text="Date approval expires", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Zone description and operational notes"
                    ),
                ),
                (
                    "hazards_identified",
                    models.TextField(
                        blank=True, help_text="Known hazards in this operational zone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is zone currently available for operations?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intersecting_airspace",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Airspace classes this zone intersects",
                        related_name="operational_zones",
                        to="aviation.airspaceclass",
                    ),
                ),
                (
                    "nearby_aerodromes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Aerodromes within proximity",
                        related_name="nearby_operational_zones",
                        to="aviation.aerodrome",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="RPAS operator this zone belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_zones",
                        to="rpas.rpasoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPAS Operational Zone",
                "verbose_name_plural": "RPAS Operational Zones",
                "ordering": ["operator", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="aerodrome",
            index=models.Index(
                fields=["aerodrome_type"], name="aviation_ae_aerodro_18deb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aerodrome",
            index=models.Index(
                fields=["is_active"], name="aviation_ae_is_acti_8e7e07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aerodrome",
            index=models.Index(
                fields=["icao_code"], name="aviation_ae_icao_co_ac23c0_idx"
            ),
        ),
    ]
