# Generated by Django 5.2.8 on 2025-11-20 12:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airspaceclass",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text="Airspace boundary geometry", srid=4326
            ),
        ),
    ]
