# Generated by Django 5.2.8 on 2025-11-24 04:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_revolutionary_compliance_system"),
        ("rpas", "0009_alter_rpastechnicallogparta_log_entry_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientBusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Full registered company name", max_length=200
                    ),
                ),
                (
                    "abn",
                    models.CharField(
                        help_text="Australian Business Number (11 digits with spaces: 12 345 678 901)",
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True,
                        help_text="Trading name if different from company name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("MINING", "Mining and Resources"),
                            ("AGRICULTURE", "Agriculture and Farming"),
                            ("CONSTRUCTION", "Construction and Engineering"),
                            ("REAL_ESTATE", "Real Estate and Property"),
                            ("MEDIA_PRODUCTION", "Media and Film Production"),
                            ("ENVIRONMENTAL", "Environmental Consulting"),
                            ("SECURITY", "Security and Surveillance"),
                            ("INSURANCE", "Insurance and Risk Assessment"),
                            ("UTILITIES", "Utilities and Infrastructure"),
                            ("GOVERNMENT", "Government and Public Sector"),
                            ("RESEARCH", "Research and Academic"),
                            ("OTHER", "Other Commercial Operations"),
                        ],
                        help_text="Primary business industry sector",
                        max_length=20,
                    ),
                ),
                (
                    "industry_sector",
                    models.CharField(
                        blank=True,
                        help_text="Specific industry subsector",
                        max_length=100,
                    ),
                ),
                (
                    "primary_service_areas",
                    models.JSONField(
                        default=list,
                        help_text="List of service types the client requires",
                    ),
                ),
                (
                    "operational_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Specific operational requirements for flight operations",
                    ),
                ),
                (
                    "public_liability_insurance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Public liability insurance coverage amount (AUD)",
                        max_digits=12,
                    ),
                ),
                (
                    "insurance_expiry_date",
                    models.DateField(help_text="Insurance policy expiry date"),
                ),
                (
                    "casa_approval_held",
                    models.BooleanField(
                        default=False,
                        help_text="Whether client holds CASA approvals for operations",
                    ),
                ),
                (
                    "casa_approval_number",
                    models.CharField(
                        blank=True,
                        help_text="CASA approval reference number if held",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Client"),
                            ("INACTIVE", "Inactive Client"),
                            ("SUSPENDED", "Suspended Client"),
                            ("PROSPECTIVE", "Prospective Client"),
                        ],
                        default="PROSPECTIVE",
                        help_text="Current client relationship status",
                        max_length=15,
                    ),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Credit Approved"),
                            ("PENDING", "Credit Under Review"),
                            ("DECLINED", "Credit Declined"),
                            ("CASH_ONLY", "Cash Only"),
                        ],
                        default="PENDING",
                        help_text="Credit approval status",
                        max_length=15,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("NET_30", "Net 30 Days"),
                            ("NET_15", "Net 15 Days"),
                            ("NET_7", "Net 7 Days"),
                            ("UPFRONT", "Payment Upfront"),
                            ("COD", "Cash on Delivery"),
                        ],
                        default="NET_30",
                        help_text="Payment terms for invoicing",
                        max_length=15,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("ONGOING", "Ongoing Services Contract"),
                            ("PROJECT", "Project-Based Contract"),
                            ("ADHOC", "Ad-hoc Services"),
                            ("TRIAL", "Trial Period"),
                        ],
                        default="TRIAL",
                        help_text="Type of service contract",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_profile",
                    models.OneToOneField(
                        help_text="Link to BaseProfile with client ProfileType",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_business",
                        to="core.baseprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Business Information",
                "verbose_name_plural": "Client Business Information",
                "db_table": "flight_operations_client_business",
            },
        ),
        migrations.CreateModel(
            name="ClientJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(help_text="Descriptive job title", max_length=200),
                ),
                (
                    "job_description",
                    models.TextField(
                        help_text="Detailed job requirements and objectives"
                    ),
                ),
                (
                    "flight_purpose",
                    models.CharField(
                        choices=[
                            ("AERIAL_WORK", "Aerial Work"),
                            ("COMMERCIAL_OPERATION", "Commercial Operation"),
                            ("RESEARCH", "Research and Development"),
                            ("TRAINING", "Training Exercise"),
                            ("EMERGENCY", "Emergency Response"),
                        ],
                        help_text="CASA flight purpose classification",
                        max_length=30,
                    ),
                ),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="MEDIUM",
                        help_text="Operational risk assessment",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft - Under Development"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("APPROVED", "Approved for Operations"),
                            ("IN_PROGRESS", "Operations In Progress"),
                            ("COMPLETED", "Operations Completed"),
                            ("CANCELLED", "Job Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Current job status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Priority"),
                            ("NORMAL", "Normal Priority"),
                            ("HIGH", "High Priority"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="Job execution priority",
                        max_length=15,
                    ),
                ),
                (
                    "requested_start_date",
                    models.DateField(help_text="Client requested start date"),
                ),
                (
                    "requested_completion_date",
                    models.DateField(help_text="Client requested completion date"),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated project cost (AUD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "casa_approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Does this job require specific CASA approvals?",
                    ),
                ),
                (
                    "casa_approval_reference",
                    models.CharField(
                        blank=True,
                        help_text="CASA approval reference number",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client business requesting the service",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_jobs",
                        to="flight_operations.clientbusinessinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Job",
                "verbose_name_plural": "Client Jobs",
                "ordering": ["-created_at", "priority", "requested_start_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("SMS", "SMS"),
                            ("APP", "App Notification"),
                        ],
                        default="EMAIL",
                        help_text="Primary communication method",
                        max_length=20,
                    ),
                ),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("REAL_TIME", "Real Time"),
                            ("DAILY", "Daily Digest"),
                            ("WEEKLY", "Weekly Summary"),
                        ],
                        default="REAL_TIME",
                        help_text="Notification frequency preference",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_flight_time",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning (6AM-12PM)"),
                            ("AFTERNOON", "Afternoon (12PM-6PM)"),
                            ("EVENING", "Evening (6PM-8PM)"),
                            ("FLEXIBLE", "Any time"),
                        ],
                        default="FLEXIBLE",
                        help_text="Preferred operation time window",
                        max_length=20,
                    ),
                ),
                (
                    "service_priority",
                    models.CharField(
                        choices=[
                            ("SPEED", "Speed"),
                            ("QUALITY", "Quality"),
                            ("COST", "Cost"),
                            ("BALANCED", "Balanced"),
                        ],
                        default="BALANCED",
                        help_text="Primary service priority",
                        max_length=15,
                    ),
                ),
                (
                    "data_sharing_consent",
                    models.BooleanField(
                        default=False, help_text="Consent to anonymized data sharing"
                    ),
                ),
                (
                    "marketing_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Consent to receive marketing communications",
                    ),
                ),
                (
                    "data_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Data retention period in days (minimum 90 for CASA compliance)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_profile",
                    models.OneToOneField(
                        help_text="Link to BaseProfile with customer ProfileType",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_preferences",
                        to="core.baseprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Preferences",
                "verbose_name_plural": "Customer Preferences",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_title",
                    models.CharField(
                        help_text="Customer description of required service",
                        max_length=200,
                    ),
                ),
                (
                    "service_description",
                    models.TextField(
                        help_text="Detailed service requirements from customer perspective"
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(help_text="Customer preferred service date"),
                ),
                (
                    "flexible_scheduling",
                    models.BooleanField(
                        default=True,
                        help_text="Can service date be adjusted if necessary?",
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("UNDER_500", "Under $500"),
                            ("500_1000", "$500 - $1,000"),
                            ("1000_2500", "$1,000 - $2,500"),
                            ("2500_5000", "$2,500 - $5,000"),
                            ("OVER_5000", "Over $5,000"),
                            ("NEGOTIABLE", "Budget Negotiable"),
                        ],
                        help_text="Customer budget expectations",
                        max_length=20,
                    ),
                ),
                (
                    "service_location",
                    models.CharField(
                        help_text="Where service needs to be performed", max_length=200
                    ),
                ),
                (
                    "location_access_restrictions",
                    models.TextField(
                        blank=True,
                        help_text="Any access restrictions or requirements at service location",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Request Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("QUOTE_PROVIDED", "Quote Provided"),
                            ("APPROVED", "Request Approved"),
                            ("CONVERTED", "Converted to Client Job"),
                            ("DECLINED", "Request Declined"),
                            ("CANCELLED", "Cancelled by Customer"),
                        ],
                        default="SUBMITTED",
                        help_text="Current request status",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine Request"),
                            ("PRIORITY", "Priority Request"),
                            ("URGENT", "Urgent Request"),
                        ],
                        default="ROUTINE",
                        help_text="Customer urgency level",
                        max_length=15,
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last contact with customer about this request",
                        null=True,
                    ),
                ),
                (
                    "next_followup_date",
                    models.DateField(
                        blank=True, help_text="Scheduled next followup date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked client job if request approved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_requests",
                        to="flight_operations.clientjob",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer requesting the service",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_jobs",
                        to="flight_operations.customerpreferences",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Job Request",
                "verbose_name_plural": "Customer Job Requests",
                "ordering": ["-created_at", "urgency", "preferred_date"],
            },
        ),
        migrations.CreateModel(
            name="FlightOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key for distributed system compatibility",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_identifier",
                    models.CharField(
                        help_text="Auto-generated identifier: FO-YYYY-NNNN format",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "task_overview",
                    models.TextField(
                        help_text="Comprehensive task description generated from job requirements"
                    ),
                ),
                (
                    "operation_manual_check",
                    models.BooleanField(
                        default=False,
                        help_text="Operation conducted in accordance with operations manual",
                    ),
                ),
                (
                    "soc_limitations_check",
                    models.BooleanField(
                        default=False,
                        help_text="Operation within standard operating condition limitations",
                    ),
                ),
                (
                    "altitude_compliance_check",
                    models.BooleanField(
                        default=False,
                        help_text="Operation maintains required altitude separation",
                    ),
                ),
                (
                    "airspace_authorization_check",
                    models.BooleanField(
                        default=False, help_text="Operation in authorized airspace only"
                    ),
                ),
                (
                    "weather_conditions_check",
                    models.BooleanField(
                        default=False,
                        help_text="Weather conditions suitable for safe operations",
                    ),
                ),
                (
                    "daylight_operations_check",
                    models.BooleanField(
                        default=False,
                        help_text="Operation conducted during daylight hours only",
                    ),
                ),
                (
                    "visual_line_sight_check",
                    models.BooleanField(
                        default=False,
                        help_text="Pilot maintains visual line of sight with aircraft",
                    ),
                ),
                (
                    "people_separation_check",
                    models.BooleanField(
                        default=False,
                        help_text="Operation maintains required separation from people",
                    ),
                ),
                (
                    "property_separation_check",
                    models.BooleanField(
                        default=False,
                        help_text="Operation maintains required separation from property",
                    ),
                ),
                (
                    "emergency_procedures_check",
                    models.BooleanField(
                        default=False,
                        help_text="Emergency procedures established and briefed",
                    ),
                ),
                (
                    "documentation_complete_check",
                    models.BooleanField(
                        default=False,
                        help_text="All required documentation complete and current",
                    ),
                ),
                (
                    "within_30m_people_maintained",
                    models.BooleanField(
                        default=False,
                        help_text="Maintain 30m separation from people maintained",
                    ),
                ),
                (
                    "clear_of_populous_areas",
                    models.BooleanField(
                        default=False, help_text="Clear of populous areas"
                    ),
                ),
                (
                    "below_400ft_agl",
                    models.BooleanField(
                        default=False, help_text="Operation below 400ft AGL"
                    ),
                ),
                (
                    "outside_restricted_area",
                    models.BooleanField(
                        default=False, help_text="Operation outside restricted areas"
                    ),
                ),
                (
                    "outside_airport_no_fly_zone",
                    models.BooleanField(
                        default=False,
                        help_text="Operation outside airport no-fly zones",
                    ),
                ),
                (
                    "outside_event_no_fly_zone",
                    models.BooleanField(
                        default=False, help_text="Operation outside event no-fly zones"
                    ),
                ),
                (
                    "operating_day_vmc",
                    models.BooleanField(
                        default=False, help_text="Operating during day VMC conditions"
                    ),
                ),
                (
                    "operating_vlos",
                    models.BooleanField(
                        default=False, help_text="Operating within visual line of sight"
                    ),
                ),
                (
                    "hazards_mitigated_by_sop",
                    models.BooleanField(
                        default=False,
                        help_text="Hazards mitigated by standard operating procedures",
                    ),
                ),
                (
                    "not_near_emergency_operations",
                    models.BooleanField(
                        default=False, help_text="Not near emergency operations"
                    ),
                ),
                (
                    "rpa_weight_2kg_or_less",
                    models.BooleanField(
                        default=False, help_text="RPA weight 2kg or less"
                    ),
                ),
                (
                    "preliminary_assessment_passed",
                    models.BooleanField(
                        default=False, help_text="Preliminary assessment passed"
                    ),
                ),
                (
                    "maximum_height_planned_ft_agl",
                    models.PositiveIntegerField(
                        help_text="Maximum planned height above ground level (feet)"
                    ),
                ),
                (
                    "requires_official_authorization",
                    models.BooleanField(
                        default=False,
                        help_text="Operation requires official CASA authorization",
                    ),
                ),
                (
                    "proposed_location_description",
                    models.TextField(
                        help_text="Detailed description of operation location"
                    ),
                ),
                (
                    "launch_location_lat",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Launch location latitude",
                        max_digits=9,
                    ),
                ),
                (
                    "launch_location_lon",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Launch location longitude",
                        max_digits=9,
                    ),
                ),
                (
                    "recovery_location_lat",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Recovery location latitude",
                        max_digits=9,
                    ),
                ),
                (
                    "recovery_location_lon",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Recovery location longitude",
                        max_digits=9,
                    ),
                ),
                (
                    "proposed_date_time",
                    models.DateTimeField(
                        help_text="Proposed date and time from scheduler"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning Phase"),
                            ("ASSESSMENT_REQUIRED", "Preliminary Assessment Required"),
                            ("JSA_REQUIRED", "Job Safety Analysis Required"),
                            ("AUTHORIZATION_PENDING", "Authorization Pending"),
                            ("APPROVED", "Approved for Execution"),
                            ("IN_PROGRESS", "Operation in Progress"),
                            ("COMPLETED", "Operation Completed"),
                            ("CANCELLED", "Operation Cancelled"),
                            ("SUSPENDED", "Operation Suspended"),
                        ],
                        default="PLANNING",
                        help_text="Current operation status",
                        max_length=25,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        help_text="Aircraft assigned to this operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_operations",
                        to="rpas.rpasaircraft",
                    ),
                ),
                (
                    "client_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated client business project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_operations",
                        to="flight_operations.clientjob",
                    ),
                ),
                (
                    "customer_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated individual customer service",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_operations",
                        to="flight_operations.customerjob",
                    ),
                ),
                (
                    "launch_location_city",
                    models.ForeignKey(
                        help_text="Launch location city",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_operations",
                        to="core.city",
                    ),
                ),
                (
                    "preliminary_assessor",
                    models.ForeignKey(
                        help_text="BaseProfile with 'pilot' ProfileType conducting assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessed_operations",
                        to="core.baseprofile",
                    ),
                ),
                (
                    "recovery_location_city",
                    models.ForeignKey(
                        help_text="Recovery location city",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_operations",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Operation",
                "verbose_name_plural": "Flight Operations",
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="clientjob",
            index=models.Index(
                fields=["status", "priority"], name="flight_oper_status_6b6984_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientjob",
            index=models.Index(
                fields=["requested_start_date"], name="flight_oper_request_8a0f3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerjob",
            index=models.Index(
                fields=["status", "urgency"], name="flight_oper_status_9ec88d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerjob",
            index=models.Index(
                fields=["preferred_date"], name="flight_oper_preferr_8015ee_idx"
            ),
        ),
    ]
