# Generated by Django 5.2.8 on 2025-11-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_revolutionary_compliance_system"),
        ("flight_operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightoperation",
            name="launch_location_city",
            field=models.ForeignKey(
                blank=True,
                help_text="Launch location city (optional - coordinates are primary)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="launch_operations",
                to="core.city",
            ),
        ),
        migrations.AlterField(
            model_name="flightoperation",
            name="recovery_location_city",
            field=models.ForeignKey(
                blank=True,
                help_text="Recovery location city (optional - coordinates are primary)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery_operations",
                to="core.city",
            ),
        ),
    ]
