# Generated by Django 5.2.8 on 2025-11-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_operations",
            "0002_alter_flightoperation_launch_location_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planning Phase"),
                    ("assessment_required", "Preliminary Assessment Required"),
                    ("jsa_required", "Job Safety Analysis Required"),
                    ("authorization_pending", "Authorization Pending"),
                    ("approved", "Approved for Execution"),
                    ("in_progress", "Operation in Progress"),
                    ("completed", "Operation Completed"),
                    ("cancelled", "Operation Cancelled"),
                    ("suspended", "Operation Suspended"),
                ],
                default="planned",
                help_text="Current operation status",
                max_length=25,
            ),
        ),
    ]
