# Generated by Django 5.2.8 on 2025-11-24 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_revolutionary_compliance_system"),
        ("flight_operations", "0003_alter_flightoperation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightoperation",
            name="launch_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Launch location city (test compatibility)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="launch_flight_operations",
                to="core.city",
            ),
        ),
        migrations.AddField(
            model_name="flightoperation",
            name="operation_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Operation coordinates as JSON (test compatibility)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flightoperation",
            name="operation_reference",
            field=models.CharField(
                blank=True,
                help_text="Alternative operation reference identifier",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="flightoperation",
            name="pilot_in_command",
            field=models.ForeignKey(
                blank=True,
                help_text="BaseProfile with 'pilot' ProfileType who will command the operation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commanded_operations",
                to="core.baseprofile",
            ),
        ),
        migrations.AddField(
            model_name="flightoperation",
            name="recovery_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Recovery location city (test compatibility)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recovery_flight_operations",
                to="core.city",
            ),
        ),
        migrations.AlterField(
            model_name="flightoperation",
            name="maximum_height_planned_ft_agl",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum planned height above ground level (feet)",
                null=True,
            ),
        ),
    ]
