# Generated by Django 5.2.8 on 2025-11-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_operations", "0004_flightoperation_launch_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightoperation",
            name="proposed_date_time",
            field=models.DateTimeField(
                blank=True, help_text="Proposed date and time from scheduler", null=True
            ),
        ),
    ]
