# Generated by Django 5.2.8 on 2025-11-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_operations", "0005_alter_flightoperation_proposed_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightoperation",
            name="launch_location_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Launch location latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flightoperation",
            name="launch_location_lon",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Launch location longitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flightoperation",
            name="recovery_location_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Recovery location latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flightoperation",
            name="recovery_location_lon",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Recovery location longitude",
                max_digits=9,
                null=True,
            ),
        ),
    ]
