# Generated by Django 5.2.8 on 2025-11-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_revolutionary_compliance_system"),
        (
            "flight_operations",
            "0006_alter_flightoperation_launch_location_lat_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightoperation",
            name="preliminary_assessor",
            field=models.ForeignKey(
                blank=True,
                help_text="BaseProfile with 'pilot' ProfileType conducting assessment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessed_operations",
                to="core.baseprofile",
            ),
        ),
    ]
