# Generated by Django 5.2.8 on 2025-11-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_operations", "0007_alter_flightoperation_preliminary_assessor"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightoperation",
            name="launch_location_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Launch location coordinates as JSON (test compatibility)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flightoperation",
            name="launch_location_point",
            field=models.JSONField(
                blank=True,
                help_text="Launch location as GeoJSON point (test compatibility)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flightoperation",
            name="recovery_location_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Recovery location coordinates as JSON (test compatibility)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flightoperation",
            name="recovery_location_point",
            field=models.JSONField(
                blank=True,
                help_text="Recovery location as GeoJSON point (test compatibility)",
                null=True,
            ),
        ),
    ]
